site_name: model-ensembler
nav:
  - Installation: installation.md
  - Usage: usage.md
  - Contributing: contributing.md
  - Acknowledgements: acknowledgements.md
  - Testimonials: testimonials.md
  - News: news.md
theme:
  name: readthedocs
  logo: https://cdn.web.bas.ac.uk/bas-style-kit/0.7.3/img/logos-symbols/bas-logo-inverse-transparent-64.png
plugins:
  - search
  - mkdocs-autoapi:
      autoapi_add_nav_entry: API
  - mkdocstrings:
      handlers:
        python:
          paths:
            - .
          options:
            show_submodules: true
            docstring_style: google
            heading_level: 3